### ISSUE TITLE
[BE] Share endpoint

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#196]
- [x] POST /api/projects/<id:uuid>/share/<user_id>
- [x] POST /api/projects/<id:uuid>/share/<user_mail>

- Creates a notification object ( #194 ) for the other user

**Comment by henderkes** [comment]
we need to add an id property to classes Role and User, in addition to further changes. 255 characters is also very short for a bio.

User has a method get_id() which will return unicode(self.id)

**Comment by aTepliak** [comment]
haven’t we decided to identify users via email?

**Comment by henderkes** [comment]
If I recall correctly and as is represented in the tasks from @Drakulix above, a user should be identifiable by both ID (identification field) and Email (required unique field)

**Comment by Drakulix** [comment]
The id is given by mongo db anyway, so it should be possible to identify the user via id as well.

**Comment by aTepliak** [comment]
I added 2 working methods , that create and add a notification EmbeddedDocument istance with
```
`
class Notification(EmbeddedDocument):
    notification_id = ObjectIdField(default=ObjectId)
    title = DB.StringField(max_length=255)
    description = DB.StringField(max_length=255)
    link = DB.URLField()
`

```
the id for every notification is automatically generated and user object looks like:
```
`{
  "_id": {
    "$oid": "5958d05db4c57f000c976c15"
  }, 
  "active": true, 
  "bookmarks": [], 
  "email": "admin@knex.com", 
  "notifications": [
   
 {
      "description": "test1", 
      "link": "http://knex.com/345", 
      "notification_id": {
        "$oid": "5958d870e2f5d8000dc42e50"
      }, 
      "title": "xyz"
    }, 
    {
      "description": "test2", 
      "link": "http://knex.com/345", 
      "notification_id": {
        "$oid": "5958da62660547000b405b20"
      }, 
      "title": "xyz"
    }


  ], 
  "password": "$pbkdf2-sha512$25000$Wut97/3/39tbK6V0zrlXyg$uu45u8.Mt2PzPMqx2MgiSZvJygyLzWb6ybDG3qR/NQFg7.gJwUS9uSv91SYZvzeRfBVLmKLiHYBNQaefd4RlFA", 
  "roles": [
    {
      "$oid": "5958d05db4c57f000c976c14"
    }
  ]
}
`
 

```

For test purpose  I've commented login_required and /id:uuid/ from id.
The problem is I couldn’t import the Notification class from __intit__.py to projects
from api.__init__ import Notification  and from backend.__init__ import Notification, import Notifications etc. didn't work.
That's why I've added the preliminary methods to __init__.py.
