### ISSUE TITLE
Google Docs API Research

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#63]
- [x] Check how to export shared file (without credentials, where possible) as something parsable (txt? rtf? maybe pdf #62 )

**Comment by Leats** [comment]
When I started looking for ways to export google docs I've also thought about other google formats. Since it was mentioned that google slides were also possibly used I looked into that one, too.

####  Export Filetypes
For __docs__: html, html(zip), txt, rtf, odt, pdf, docx, epub
For __presentations__: pptx, odp, pdf, txt, jpg, png, svg
For our purposes txt should be enough and easiest, so there is no problem with docs and presentations. 

#### Permissions needed
To export the file it needs to either be public or shared so that there won't be trouble with permissions. This is true for the shared type where everyone having the link can open it. Otherwise one has to actually ask for permission, obviously. But I guess since the link will be shared on the knex, it will be either public or link-shared(?). 

#### Exporting
The things needed for exporting are both the ID of the document, which you have with the link, plus the type you want to export it in.
[See the Google Drive REST API](https://developers.google.com/drive/v3/web/manage-downloads#downloading_google_documents), though the API needs credentials to be used
Alternatively, the direct download link for google docs in the desired formats, if that helps:

```
Google Document : https://docs.google.com/document/d/[FILE_ID]/export?format=[FORMAT]
FORMAT : docx, odt, rtf, pdf, txt, html

Google Presentation : https://docs.google.com/presentation/d/[FILE_ID]/export?format=[FORMAT]
FORMAT : pptx, pdf, svg, png, jpg 
```
