### ISSUE TITLE
[FE] Add Pagination for ProjectDiscovery

### ISSUE THREAD

**Issue by Rintel** [Drakulix/knex#71]
Complexity: M

This should include fetching only 15 elements/projects per page! We can adjust the amount of projects later on.

**Comment by Phil-Schmidt** [comment]
Our progress so far can be found in the branch feature/Pagination/iss71.
Due to the fact that this feature is dependent on test features that are not supposed to be merged into the master I have refrained from starting a pull request until either that decision is revoked or a separate development master branch is established.
